stages:
  - test

test_lint_and_unit:
  stage: test
  image: node:18
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run lint
    - npm test
  only:
    - main
    - merge_requests